In [118]:
import pandas as pd

ModuleNotFoundError: No module named 'git'

In [96]:
data = pd.read_csv('tabela.csv', sep =';')
#data = pd.read_excel('tabela.xlsx')

In [97]:
data

,codigo_municipio,nome_municipio,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,3100104,Abadia dos Dourados (MG),6659,8901,11262,11470,12743,16157,19307,20140,20587,26214,27977,36810,40741,42402,50704,33304,31476
1,3100203,Abaeté (MG),15259,19137,22992,23062,22519,29851,42422,31918,31883,38658,35028,44696,49993,45170,113998,96146,98806
2,3100302,Abre Campo (MG),13217,11745,13107,16912,16159,14940,16384,18405,20715,35298,28391,22897,27317,36432,43850,30077,26828
3,3100401,Acaiaca (MG),1111,1484,1694,1550,1534,1790,2398,2790,2822,3155,2977,3381,3211,2410,3845,2519,2086
4,3100500,Açucena (MG),5253,5844,5885,7081,9160,6554,7394,8848,7559,10758,8192,12229,16057,13098,17131,15239,10667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
848,3171808,Virginópolis (MG),3889,4978,4844,5223,7892,9463,9760,9284,7824,8828,9802,25880,28650,22572,23109,22403,20219
849,3171907,Virgolândia (MG),2187,2474,2878,2981,2921,3537,3742,4060,3744,4834,4985,7009,6616,6241,6329,6079,5783
850,3172004,Visconde do Rio Branco (MG),3914,5968,6720,6429,6300,7167,9149,9440,8411,10715,11383,16256,14839,10133,13053,9463,11064
851,3172103,Volta Grande (MG),2221,2655,3159,3005,2867,3346,3061,3924,4885,4176,4000,4655,4565,4666,7529,6233,6026
852,3172202,Wenceslau Braz (MG),1292,1290,1816,1962,1920,2744,3088,2994,3066,5682,3312,4506,4962,3744,2929,2611,3635

In [98]:
"""
indexar colunas e passar as demais para linhas
Exemplo: indexar codigo_municipio e nome_municipio
passar uma coluna para anos, e uma pra valor
"""

data = pd.melt(data.reset_index(), id_vars=['codigo_municipio', 'nome_municipio'], 
var_name='ano', value_name='valor')

In [99]:
data

       codigo_municipio               nome_municipio    ano  valor
0               3100104     Abadia dos Dourados (MG)  index      0
1               3100203                  Abaeté (MG)  index      1
2               3100302              Abre Campo (MG)  index      2
3               3100401                 Acaiaca (MG)  index      3
4               3100500                 Açucena (MG)  index      4
...                 ...                          ...    ...    ...
15349           3171808            Virginópolis (MG)   2018  20219
15350           3171907             Virgolândia (MG)   2018   5783
15351           3172004  Visconde do Rio Branco (MG)   2018  11064
15352           3172103            Volta Grande (MG)   2018   6026
15353           3172202          Wenceslau Braz (MG)   2018   3635

[15354 rows x 4 columns]

In [114]:
#retirar os index e da uma limpada no arquivo
data = data[data.ano.str.contains("index") == False]
data.head(50)

     codigo_municipio               nome_municipio   ano  valor
853           3100104     Abadia dos Dourados (MG)  2002   6659
854           3100203                  Abaeté (MG)  2002  15259
855           3100302              Abre Campo (MG)  2002  13217
856           3100401                 Acaiaca (MG)  2002   1111
857           3100500                 Açucena (MG)  2002   5253
858           3100609                Água Boa (MG)  2002  11188
859           3100708           Água Comprida (MG)  2002  12851
860           3100807                 Aguanil (MG)  2002   3592
861           3100906          Águas Formosas (MG)  2002   4042
862           3101003         Águas Vermelhas (MG)  2002  32023
863           3101102                 Aimorés (MG)  2002  12189
864           3101201                Aiuruoca (MG)  2002   4281
865           3101300                  Alagoa (MG)  2002   1485
866           3101409               Albertina (MG)  2002   1768
867           3101508            Além Paraíba (MG)  2002   3944
868           3101607                 Alfenas (MG)  2002  37455
869           3101631     Alfredo Vasconcelos (MG)  2002   3935
870           3101706                Almenara (MG)  2002   7269
871           3101805               Alpercata (MG)  2002   2052
872           3101904             Alpinópolis (MG)  2002  13024
873           3102001                Alterosa (MG)  2002   9721
874           3102050            Alto Caparaó (MG)  2002   2440
875           3102100           Alto Rio Doce (MG)  2002   9525
876           3102209               Alvarenga (MG)  2002   1675
877           3102308             Alvinópolis (MG)  2002   8645
878           3102407       Alvorada de Minas (MG)  2002   1800
879           3102506         Amparo do Serra (MG)  2002   1908
880           3102605                Andradas (MG)  2002  23695
881           3102704      Cachoeira de Pajeú (MG)  2002   6972
882           3102803             Andrelândia (MG)  2002   7711
883           3102852              Angelândia (MG)  2002   3714
884           3102902          Antônio Carlos (MG)  2002   4190
885           3103009            Antônio Dias (MG)  2002  11074
886           3103108  Antônio Prado de Minas (MG)  2002    818
887           3103207                  Araçaí (MG)  2002   1255
888           3103306               Aracitaba (MG)  2002    679
889           3103405                 Araçuaí (MG)  2002   3629
890           3103504                Araguari (MG)  2002  92320
891           3103603                Arantina (MG)  2002   3680
892           3103702                Araponga (MG)  2002   3330
893           3103751                 Araporã (MG)  2002  10818
894           3103801                  Arapuá (MG)  2002   2313
895           3103900                 Araújos (MG)  2002  19957
896           3104007                   Araxá (MG)  2002  24200
897           3104106               Arceburgo (MG)  2002   6180
898           3104205                   Arcos (MG)  2002   7070
899           3104304                  Areado (MG)  2002   9082
900           3104403                Argirita (MG)  2002   1144
901           3104452              Aricanduva (MG)  2002   2049
902           3104502                  Arinos (MG)  2002  12201

In [115]:
data.to_csv(r'C:\Users\André Neto\Documents\Zetta\output.csv')
#data.to_excel(r'C:\Users\André Neto\Documents\Zetta\output.xlsx')

In [116]:
echo "# aeneto" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin git@github.com:aeneto/aeneto.git
git push -u origin main

SyntaxError: invalid syntax (<ipython-input-116-e0bb15e7849d>, line 1)